name: Deploy to Production

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Verify Node.js and npm versions
        run: |
          node --version
          npm --version

      - name: Build React app
        run: |
          cd weather-app
          npm run build

      - name: Deploy to Server
        run: |
          scp -r weather-app/build/* user@server:/path/to/deployment/directory
